[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = [
  "mkdir -p java-leaderboard/bin",
  "cd java-leaderboard && javac -cp 'libs/*:src' -d bin src/com/insightxr/App.java src/com/insightxr/FirebaseInit.java src/com/insightxr/service/ILeaderboard.java src/com/insightxr/service/LeaderboardService.java src/com/insightxr/service/InMemoryLeaderboardService.java"
]

[start]
cmd = "cd java-leaderboard && java -cp 'libs/*:bin' com.insightxr.App"
