[build]
builder = "DOCKERFILE"
dockerfilePath = "java-leaderboard/Dockerfile"

[deploy]
startCommand = "java -cp 'libs/*:bin' com.insightxr.App"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
